name: snapchat
description: A Snapchat UI Clone.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.1
  emojis: ^0.9.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bitmoji/
    - assets/chat/
  fonts:
    - family: Metropolis
      fonts:
        - asset: fonts/Metropolis-Black.otf
        - asset: fonts/Metropolis-Bold.otf
        - asset: fonts/Metropolis-ExtraBold.otf
        - asset: fonts/Metropolis-ExtraLight.otf
        - asset: fonts/Metropolis-Light.otf
        - asset: fonts/Metropolis-Medium.otf
        - asset: fonts/Metropolis-Regular.otf
        - asset: fonts/Metropolis-SemiBold.otf
        - asset: fonts/Metropolis-Thin.otf
         
